[package]
name = "bumbam"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"
byteorder = "1.4"
clap = { version = "3.0.10", features = ["yaml"] }
